- name: precedence checks
  hosts: local
  connection: local
  # become: yes
  # vars:
  #   NAME: "I am from PLAY level"
  # vars_files:
  #   - custom.yaml
  # vars_prompt:
  #   - name: NAME
  #     prompt: "Please enter user name"
  #     private: false
  
  tasks:
  - name: print precedence value
    ansible.builtin.debug:
      msg: "Variable location: {{ NAME }}"
    # vars:
    #   NAME: "I am from TASK level"

# precedence order top to bottom:

# command line args
# task level
# file level
# prompt level
# play level
# inventory level